### ISSUE TITLE
entities start, end index 추출 관련 문의

### ISSUE THREAD

**Issue by kksbell** [CS408-WorkoutBuddy/WorkoutBuddy#1]
안녕하세요.

글을 남길 곳을 마땅히 찾지 못해서 이슈로 올리는점 양해 부탁드립니다.

다름이 아니라,

RASA pipeline 한글화 에서

CRFEntityExtractorKorean
Tokenizer에서 parsing한 정보와 원래 문장에서의 entity위치 정보를 토대로 entity를 추출하는 pipeline입니다.
기존 Extractor에서는 단순히 string에 대해 index함수를 직접 적용하여 원래 문장에서 entity 위치를 검색하는 방식이었지만, 한글의 경우 형태소로 추출하게 되면 원래 문장과 모양이 변하게 되는 경우가 빈번하여 string에 직접 index 함수를 적용할 수 없습니다.
그래서 기존 CRFEntityExtractor 코드를 한글에 맞도록 약간 변경하였습니다.

라고 설명해주셨는데

원문에서 추출한 entity start, end index를
형태소 추출 후의 변형된 문장과 어떻게 비교하셨는지 궁금합니다!

**Comment by gusbea1** [comment]
안녕하세요, 질문을 한달이나 늦게 봤네요.. 
반년 전에 정신없게 만들었던 코드라 정확히는 기억이 안납니다만, 기억나는대로 말씀드리겠습니다.
우선 Tokenizer에서 extractor로 전달할 때 각 형태소마다 원래 문장의 offset을 붙여서 list로 전달했습니다.
(entity, offset) 들의 list형식으로 전달한 후 Extractor에서 entity 형태소에 해당하는 원소들의 offset을 참조하였습니다. (아마 offset의 형식 또한 (원래문장에서 시작지점, 원래문장에서 끝나는지점) 의 튜플이었던 걸로 기억합니다)
원래 문장에서 형태소의 위치를 찾아내는것(offset붙이는것)이 궁금하신것 같은데, 형태소 모양이 원문과 같은 경우는 평범하게 진행하였고, 못 찾을 경우에는 지금까지의 offset으로부터 형태소의 길이만큼을 참고해서 넣어주었던 것 같습니다. 거의 대부분의 경우 형태소의 길이가 원문에서의 단어 길이보다는 짧다는 것을 이용했던 것 같습니다. 한글에서는 예외는 못 찾았던 것 같지만 외래어에서는 안 되는 경우도 있어서 완벽한 코드는 아닙니다.
어떻게 써도 설명하기가 좀 어렵네요.. Tokenizer for문의 try 구문을 보시면 될거같습니다.

**Comment by gusbea1** [comment]
> 안녕하세요.
> 
> 글을 남길 곳을 마땅히 찾지 못해서 이슈로 올리는점 양해 부탁드립니다.
> 
> 다름이 아니라,
> 
> RASA pipeline 한글화 에서
> 
> CRFEntityExtractorKorean
> Tokenizer에서 parsing한 정보와 원래 문장에서의 entity위치 정보를 토대로 entity를 추출하는 pipeline입니다.
> 기존 Extractor에서는 단순히 string에 대해 index함수를 직접 적용하여 원래 문장에서 entity 위치를 검색하는 방식이었지만, 한글의 경우 형태소로 추출하게 되면 원래 문장과 모양이 변하게 되는 경우가 빈번하여 string에 직접 index 함수를 적용할 수 없습니다.
> 그래서 기존 CRFEntityExtractor 코드를 한글에 맞도록 약간 변경하였습니다.
> 
> 라고 설명해주셨는데
> 
> 원문에서 추출한 entity start, end index를
> 형태소 추출 후의 변형된 문장과 어떻게 비교하셨는지 궁금합니다!

**Comment by kksbell** [comment]
제 나름대로 생각을 해서 만들어 봤지만
말씀해주신 방법으로 다시 한번 해볼게요~
한달이 지난 게시물인데 답글 달아주셔서 감사합니다~!!
즐거운 하루 보내세요~!!
